url: https://dm.quicksearch.se/QSNetComponents/QS.Org/default.aspx?HolderGroupId=%7BB1D742BA-92A6-49A3-AFC5-FAD6D7016860%7D&RootGroupdId=%7BE4F30D0D-D812-4EE8-AAB4-89E4C2204C03%7D&ContractId=%7BABF0D62C-E7EA-419A-AD76-C7EADAA134E5%7D&LanguageId=%7BA1DE86C9-934F-4FCE-B753-9F01AEDBB8BE%7D&UserId=%7BD5113524-69DA-43BA-A898-36F2678CA2C7%7D&circular_id=%7B7EB91046-7E2B-4112-ABDD-864EC69EC9C5%7D&Freq=True&antiCsrfToken=11151249041l163190

divisions:
  IT: [TKITE, MPIDE, MPSOF, MPDSC]
  D: [TKDAT, MPALG, MPCSN, MPHPC]
  A: [TKARK, TKATK, MPARC, MPDSD]
  AE: [TAFFS]
  E: [TKELT, TKMED, MPBME, MPCOM, MPEES, MPEPO, MPWPS]
  F: [TKTFY, MPAPP, MPCAS, MPNAT, MPPAS, MPPHS, TKTEM, MPENM, MPLOL]
  H: [TIDAL, TIMEL, TIMAL, TIDSL, TIELL, TIEPL]
  I: [TKIEK, MPBDP, MPMEI, MPQOM, MPSCM]
  K: [TKKMT, TIKEL, MPMCN]
  KFKB: [TKBIO, TKKEF, MPBIO, MPISC, TKGBS]
  M: [TKMAS, MPAEM, MPAME, MPAUT, MPPDE, MPPEN, MPNAV, MPTSE]
  Sjö: [TISJL, TSILO, TSJKL, TSLOG, MPMAR, SBVII]
  TB: [ZBASD, ZBASS]
  TD: [TKDES, MPDES]
  V: [TKSAM, TISAM, MPDCF, MPDCM, MPIEE, MPSEB, MPSOV]
  Z: [TKAUT, MPSYS]
  Other: [KPLOL]